<a href="https://colab.research.google.com/github/AdrianAlbrecht/Collab/blob/main/Biolog_naprawa_pliku.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [126]:
import pandas as pd
import glob

In [127]:
# Ścieżka do katalogu zawierającego pliki CSV
sciezka_do_katalogu = ''
# Zidentyfikuj pliki CSV w danym katalogu
pliki_csv = glob.glob(sciezka_do_katalogu + '*.csv')

In [128]:
ramka_danych = pd.concat((pd.read_csv(plik, sep=";", header=None) for plik in pliki_csv), ignore_index=True)
ramka_danych

,0,1,2,3,4,5,6,7,8,9,...,245,246,247,248,249,250,251,252,253,254
0,Aeluropus.lagopoides (MK622397.1),18,A,G,G,G,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aeluropus.lagopoides (MK622397.1),18,A,G,G,G,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aeluropus.lagopoides (MK622397.1),244,A,G,G,G,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aeluropus.lagopoides (MK622397.1),1681,A,G,G,G,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aeluropus.lagopoides (MK622397.1),1746,G,C,C,C,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4226,Setaria.viridis (KT289405.1),113697,-,C,C,C,C,C,C,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4227,Setaria.viridis (KT289405.1),113698,-,G,G,T,G,G,G,G,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4228,Setaria.viridis (KT289405.1),115871,-,A,A,T,A,A,A,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4229,Setaria.viridis (KT289405.1),115872,-,A,A,A,A,A,A,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4230,Setaria.viridis (KT289405.1),116652,A,T,T,T,T,T,T,T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [129]:
# Usuń kolumny zawierające same NaN
ramka_danych = ramka_danych.dropna(axis=1, how='all')
ramka_danych

,0,1,2,3,4,5,6,7,8,9,10,11
0,Aeluropus.lagopoides (MK622397.1),18,A,G,G,G,NaN,NaN,NaN,NaN,NaN,NaN
1,Aeluropus.lagopoides (MK622397.1),18,A,G,G,G,NaN,NaN,NaN,NaN,NaN,NaN
2,Aeluropus.lagopoides (MK622397.1),244,A,G,G,G,NaN,NaN,NaN,NaN,NaN,NaN
3,Aeluropus.lagopoides (MK622397.1),1681,A,G,G,G,NaN,NaN,NaN,NaN,NaN,NaN
4,Aeluropus.lagopoides (MK622397.1),1746,G,C,C,C,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
4226,Setaria.viridis (KT289405.1),113697,-,C,C,C,C,C,C,C,C,C
4227,Setaria.viridis (KT289405.1),113698,-,G,G,T,G,G,G,G,G,T
4228,Setaria.viridis (KT289405.1),115871,-,A,A,T,A,A,A,A,A,T
4229,Setaria.viridis (KT289405.1),115872,-,A,A,A,A,A,A,A,A,A
4230,Setaria.viridis (KT289405.1),116652,A,T,T,T,T,T,T,T,T,T

In [130]:
# Zidentyfikuj unikalne wartości w pierwszej kolumnie
unikalne_wartosci = ramka_danych.iloc[:, 0].unique()
# Stwórz słownik
slownik_wartosci = {klucz: [0]*8 for klucz in unikalne_wartosci}
# Stwórz słownik, gdzie klucze to unikalne wartości, a wartościami są ramki danych
ramki_danych_slownik = {wartosc: ramka_danych[ramka_danych.iloc[:, 0] == wartosc] for wartosc in unikalne_wartosci}

In [133]:
for klucz, ramka in ramki_danych_slownik.items():
  # Usuwamy NaN'y
  ramka = ramka.copy()
  ramka = ramka.dropna(axis=1, how='all')
  # Dzielimy na Single i Multi
  ramka['Single/Multi'] = 'Multi'
  indeksy_multi = ramka[(ramka.iloc[:, 1].diff() != 1) & (ramka.iloc[:, 1].shift(-1).diff() != 1)].index
  ramka.loc[indeksy_multi, 'Single/Multi'] = 'Single'
  # Indeksy do usuniecia (Multi ma być liczone jako jeden)
  indeksy_do_usuniecia = ramka[(ramka['Single/Multi'] == 'Multi') & (ramka['Single/Multi'].shift(-1) == 'Multi')\
                                      & (ramka.iloc[:, 1] + 1 == ramka.iloc[:, 1].shift(-1))].index
  # Usuń niepotrzebne wiersze multi
  ramka = ramka.drop(index=indeksy_do_usuniecia)
  # Określamy operację
  # insercja T - - - - -
  # delecja - T T T T T
  # substytucja C A A A A A
  # mixed A C T G C C C A
  ramka['Operation'] = 'Mixed'
  # Znajdź indeksy dla substytucji
  indeksy_substitution = ramka.loc[(ramka.iloc[:, 2] != '-') & (ramka.iloc[:, 3:-2].eq(ramka.iloc[:, 3], axis=0).all(axis=1))].index
  # Znajdź indeksy dla insercji
  indeksy_insertion = ramka.loc[(ramka.iloc[:, 2] != '-') & (ramka.iloc[:, 3:-2].eq("-", axis=0).all(axis=1))].index
  # Znajdź indeksy dla delecji
  indeksy_deletion = ramka.loc[(ramka.iloc[:, 2] == '-') & (ramka.iloc[:, 3:-2].eq(ramka.iloc[:, 3], axis=0).all(axis=1))].index
  # Ustaw wartość operacji dla odpowiednich wierszy w kolumnie "Operation"
  ramka.loc[indeksy_substitution, 'Operation'] = 'Substitution'
  ramka.loc[indeksy_insertion, 'Operation'] = 'Insertion'
  ramka.loc[indeksy_deletion, 'Operation'] = 'Deletion'
  #Liczymy wartości
  slownik_wartosci[klucz] = [\
      ((ramka.iloc[:, -1] == 'Substitution') & (ramka.iloc[:, -2] == 'Single')).sum(),\
      ((ramka.iloc[:, -1] == 'Deletion') & (ramka.iloc[:, -2] == 'Single')).sum(),\
      ((ramka.iloc[:, -1] == 'Insertion') & (ramka.iloc[:, -2] == 'Single')).sum(),\
      ((ramka.iloc[:, -1] == 'Mixed') & (ramka.iloc[:, -2] == 'Single')).sum(),\
      ((ramka.iloc[:, -1] == 'Substitution') & (ramka.iloc[:, -2] == 'Multi')).sum(),\
      ((ramka.iloc[:, -1] == 'Deletion') & (ramka.iloc[:, -2] == 'Multi')).sum(),\
      ((ramka.iloc[:, -1] == 'Insertion') & (ramka.iloc[:, -2] == 'Multi')).sum(),\
      ((ramka.iloc[:, -1] == 'Mixed') & (ramka.iloc[:, -2] == 'Multi')).sum()\
  ]

In [134]:
# Przekształć słownik na ramkę danych
dataset = pd.DataFrame(list(slownik_wartosci.items()), columns=['Species', 'Values'])
# Rozbij listę na pojedyncze wartości i umieść jako nowe kolumny
dataset[['Single Substitution', 'Single Deletion', 'Single Insertion', 'Single Mixed', \
          'Multi Substitution', 'Multi Deletion', 'Multi Insertion', 'Multi Mixed']] = pd.DataFrame(dataset['Values'].tolist(), index=dataset.index)
# Usuń niepotrzebną kolumnę 'Wartosci'
dataset = dataset.drop('Values', axis=1)
dataset

,Species,Single Substitution,Single Deletion,Single Insertion,Single Mixed,Multi Substitution,Multi Deletion,Multi Insertion,Multi Mixed
0,Aeluropus.lagopoides (MK622397.1),176,5,6,7,1,2,6,0
1,Aeluropus.littoralis (MT040977.1),112,10,3,7,4,5,4,1
2,Aeluropus.sinensis (MW194080.1),281,8,9,5,8,15,28,1
3,Setaria.geminata (KU291476.1),586,12,11,91,12,19,40,15
4,Setaria.italica (KF646538.1),8,0,2,8,0,2,1,1
5,Setaria.viridis (KT289405.1),10,2,3,5,2,23,20,3

In [136]:
dataset.to_csv('MDCS_without_length.csv', sep=";", index=False)