<a href="https://colab.research.google.com/github/AdrianAlbrecht/Collab/blob/main/WS_zad_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [106]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.10/dist-packages (0.0.3)

In [107]:
import pandas as pd

In [108]:
from ucimlrepo import fetch_ucirepo #import dostępu do repozytorium ze strony http://archive.ics.uci.edu/dataset

heart_disease = fetch_ucirepo(id=45) #pobieranie datasetu heart_diesese: http://archive.ics.uci.edu/dataset/45/heart+disease

X = heart_disease.data.features
y = heart_disease.data.targets

# metadane
print(heart_disease.metadata)

# informacje o atrybutach
print(heart_disease.variables)

{'uci_id': 45, 'name': 'Heart Disease', 'repository_url': 'https://archive.ics.uci.edu/dataset/45/heart+disease', 'data_url': 'https://archive.ics.uci.edu/static/public/45/data.csv', 'abstract': '4 databases: Cleveland, Hungary, Switzerland, and the VA Long Beach', 'area': 'Life Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 303, 'num_features': 13, 'feature_types': ['Categorical', 'Integer', 'Real'], 'demographics': ['Age', 'Sex'], 'target_col': ['num'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1989, 'last_updated': 'Mon Aug 28 2023', 'dataset_doi': '10.24432/C52P4X', 'creators': ['Andras Janosi', 'William Steinbrunn', 'Matthias Pfisterer', 'Robert Detrano'], 'intro_paper': {'title': 'International application of a new probability algorithm for the diagnosis of coronary artery disease.', 'authors': 'R. Detrano, A. Jánosi, W. Steinbrunn, M. Pfisterer, J. Schmid, S. Sandhu, K. Guppy, S. Lee, V. Froelicher', 'published_in': 'American Journal of Cardiology', 'year': 1989, 'url': 'https://www.semanticscholar.org/paper/a7d714f8f87bfc41351eb5ae1e5472f0ebbe0574', 'doi': None}, 'additional_info': {'summary': 'This database contains 76 attributes, but all published experiments refer to using a subset of 14 of them.  In particular, the Cleveland database is the only one that has been used by ML researchers to date.  The "goal" field refers to the presence of heart disease in the patient.  It is integer valued from 0 (no presence) to 4. Experiments with the Cleveland database have concentrated on simply attempting to distinguish presence (values 1,2,3,4) from absence (value 0).  \n   \nThe names and social security numbers of the patients were recently removed from the database, replaced with dummy values.\n\nOne file has been "processed", that one containing the Cleveland database.  All four unprocessed files also exist in this directory.\n\nTo see Test Costs (donated by Peter Turney), please see the folder "Costs" ', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Only 14 attributes used:\r\n      1. #3  (age)       \r\n      2. #4  (sex)       \r\n      3. #9  (cp)        \r\n      4. #10 (trestbps)  \r\n      5. #12 (chol)      \r\n      6. #16 (fbs)       \r\n      7. #19 (restecg)   \r\n      8. #32 (thalach)   \r\n      9. #38 (exang)     \r\n      10. #40 (oldpeak)   \r\n      11. #41 (slope)     \r\n      12. #44 (ca)        \r\n      13. #51 (thal)      \r\n      14. #58 (num)       (the predicted attribute)\r\n\r\nComplete attribute documentation:\r\n      1 id: patient identification number\r\n      2 ccf: social security number (I replaced this with a dummy value of 0)\r\n      3 age: age in years\r\n      4 sex: sex (1 = male; 0 = female)\r\n      5 painloc: chest pain location (1 = substernal; 0 = otherwise)\r\n      6 painexer (1 = provoked by exertion; 0 = otherwise)\r\n      7 relrest (1 = relieved after rest; 0 = otherwise)\r\n      8 pncaden (sum of 5, 6, and 7)\r\n      9 cp: chest pain type\r\n        -- Value 1: typical angina\r\n        -- Value 2: atypical angina\r\n        -- Value 3: non-anginal pain\r\n        -- Value 4: asymptomatic\r\n     10 trestbps: resting blood pressure (in mm Hg on admission to the hospital)\r\n     11 htn\r\n     12 chol: serum cholestoral in mg/dl\r\n     13 smoke: I believe this is 1 = yes; 0 = no (is or is not a smoker)\r\n     14 cigs (cigarettes per day)\r\n     15 years (number of years as a smoker)\r\n     16 fbs: (fasting blood sugar > 120 mg/dl)  (1 = true; 0 = false)\r\n     17 dm (1 = history of diabetes; 0 = no such history)\r\n     18 famhist: family history of coronary artery disease (1 = yes; 0 = no)\r\n     19 restecg: resting electrocardiographic results\r\n        -- Value 0: normal\r\n        -- Value 1: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV)\r\n        -- Value 2: showing probable or definite left ventricular hypertrophy by Estes\' criteria\r\n     20 ekgmo (month of exercise ECG reading)\r\n     21 ekgday(day of exercise ECG reading)\r\n     22 ekgyr (year of exercise ECG reading)\r\n     23 dig (digitalis used furing exercise ECG: 1 = yes; 0 = no)\r\n     24 prop (Beta blocker used during exercise ECG: 1 = yes; 0 = no)\r\n     25 nitr (nitrates used during exercise ECG: 1 = yes; 0 = no)\r\n     26 pro (calcium channel blocker used during exercise ECG: 1 = yes; 0 = no)\r\n     27 diuretic (diuretic used used during exercise ECG: 1 = yes; 0 = no)\r\n     28 proto: exercise protocol\r\n          1 = Bruce     \r\n          2 = Kottus\r\n          3 = McHenry\r\n          4 = fast Balke\r\n          5 = Balke\r\n          6 = Noughton \r\n          7 = bike 150 kpa min/min  (Not sure if "kpa min/min" is what was written!)\r\n          8 = bike 125 kpa min/min  \r\n          9 = bike 100 kpa min/min\r\n         10 = bike 75 kpa min/min\r\n         11 = bike 50 kpa min/min\r\n         12 = arm ergometer\r\n     29 thaldur: duration of exercise test in minutes\r\n     30 thaltime: time when ST measure depression was noted\r\n     31 met: mets achieved\r\n     32 thalach: maximum heart rate achieved\r\n     33 thalrest: resting heart rate\r\n     34 tpeakbps: peak exercise blood pressure (first of 2 parts)\r\n     35 tpeakbpd: peak exercise blood pressure (second of 2 parts)\r\n     36 dummy\r\n     37 trestbpd: resting blood pressure\r\n     38 exang: exercise induced angina (1 = yes; 0 = no)\r\n     39 xhypo: (1 = yes; 0 = no)\r\n     40 oldpeak = ST depression induced by exercise relative to rest\r\n     41 slope: the slope of the peak exercise ST segment\r\n        -- Value 1: upsloping\r\n        -- Value 2: flat\r\n        -- Value 3: downsloping\r\n     42 rldv5: height at rest\r\n     43 rldv5e: height at peak exercise\r\n     44 ca: number of major vessels (0-3) colored by flourosopy\r\n     45 restckm: irrelevant\r\n     46 exerckm: irrelevant\r\n     47 restef: rest raidonuclid (sp?) ejection fraction\r\n     48 restwm: rest wall (sp?) motion abnormality\r\n        0 = none\r\n        1 = mild or moderate\r\n        2 = moderate or severe\r\n        3 = akinesis or dyskmem (sp?)\r\n     49 exeref: exercise radinalid (sp?) ejection fraction\r\n     50 exerwm: exercise wall (sp?) motion \r\n     51 thal: 3 = normal; 6 = fixed defect; 7 = reversable defect\r\n     52 thalsev: not used\r\n     53 thalpul: not used\r\n     54 earlobe: not used\r\n     55 cmo: month of cardiac cath (sp?)  (perhaps "call")\r\n     56 cday: day of cardiac cath (sp?)\r\n     57 cyr: year of cardiac cath (sp?)\r\n     58 num: diagnosis of heart disease (angiographic disease status)\r\n        -- Value 0: < 50% diameter narrowing\r\n        -- Value 1: > 50% diameter narrowing\r\n        (in any major vessel: attributes 59 through 68 are vessels)\r\n     59 lmt\r\n     60 ladprox\r\n     61 laddist\r\n     62 diag\r\n     63 cxmain\r\n     64 ramus\r\n     65 om1\r\n     66 om2\r\n     67 rcaprox\r\n     68 rcadist\r\n     69 lvx1: not used\r\n     70 lvx2: not used\r\n     71 lvx3: not used\r\n     72 lvx4: not used\r\n     73 lvf: not used\r\n     74 cathef: not used\r\n     75 junk: not used\r\n     76 name: last name of patient  (I replaced this with the dummy string "name")', 'citation': None}}
        name     role         type demographic  \
0        age  Feature      Integer         Age
1        sex  Feature  Categorical         Sex
2         cp  Feature  Categorical        None
3   trestbps  Feature      Integer        None
4       chol  Feature      Integer        None
5        fbs  Feature  Categorical        None
6    restecg  Feature  Categorical        None
7    thalach  Feature      Integer        None
8      exang  Feature  Categorical        None
9    oldpeak  Feature      Integer        None
10     slope  Feature  Categorical        None
11        ca  Feature      Integer        None
12      thal  Feature  Categorical        None
13       num   Target      Integer        None

                                              description  units  \
0                                                    None  years
1                                                    None   None
2                                                    None   None
3   resting blood pressure (on admission to the hospital)  mm Hg
4                                       serum cholestoral  mg/dl
5                         fasting blood sugar > 120 mg/dl   None
6                                                    None   None
7                             maximum heart rate achieved   None
8                                 exercise induced angina   None
9      ST depression induced by exercise relative to rest   None
10                                                   None   None
11    number of major vessels (0-3) colored by flourosopy   None
12                                                   None   None
13                             diagnosis of heart disease   None

   missing_values
0              no
1              no
2              no
3              no
4              no
5              no
6              no
7              no
8              no
9              no
10             no
11            yes
12            yes
13             no



---


# Widzimy, że w atrybutach numer 11 i 12 (są to kolejno atrybuty "ca" i "thal") są brakujące wartości. Trzeba sprawdzić co się da z nimi zrobić.


---

# Łączymy w zmienną df cały dataset, podziałka na X i Y przyda nam się w dalszych ćwiczeniach.

In [109]:
df = pd.concat([X, y], axis=1)

In [110]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63,1,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2
2,67,1,4,120,229,0,2,129,1,2.6,2,2.0,7.0,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,3.0,0

In [111]:
df[df.isna().any(axis=1)]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
87,53,0,3,128,216,0,2,115,0,0.0,1,0.0,NaN,0
166,52,1,3,138,223,0,0,169,0,0.0,1,NaN,3.0,0
192,43,1,4,132,247,1,2,143,1,0.1,2,NaN,7.0,1
266,52,1,4,128,204,1,0,156,1,1.0,2,0.0,NaN,2
287,58,1,2,125,220,0,0,144,0,0.4,2,NaN,7.0,0
302,38,1,3,138,175,0,0,173,0,0.0,1,NaN,3.0,0

# Powyżej wyświetliliśmy wiersze (rekordy) posiadające brakujące warttości. Teraz pokażemy ile jest ich pod względem ilości całości datasetu.

In [112]:
df.shape[0] #ilość wszystkich wierszy

303

In [113]:
df[df.isna().any(axis=1)].shape[0] #ilość wierszy z brakującymi wartościami

6

# Jak widać rekordów z brakującymi wartościami jest stosunkowo mało, dlatego moim zdaniem możemy te rekordy usunąć.

In [114]:
df.dropna(inplace=True)
df.shape[0]

297

# Usunęliśmy zbędne wiersze. Przejrzyjmy jeszcze raz informacje na temat atrybutów.

In [115]:
pd.set_option('display.max_colwidth', None)
heart_disease.variables['description']

0                                                      None
1                                                      None
2                                                      None
3     resting blood pressure (on admission to the hospital)
4                                         serum cholestoral
5                           fasting blood sugar > 120 mg/dl
6                                                      None
7                               maximum heart rate achieved
8                                   exercise induced angina
9        ST depression induced by exercise relative to rest
10                                                     None
11      number of major vessels (0-3) colored by flourosopy
12                                                     None
13                               diagnosis of heart disease
Name: description, dtype: object

# Atrybut numer 5 mówi o tym czy cukier w próbce krwii jest powyżej 120mg/dl. Powinna być to wartosc 0 (False) lub 1(True). Wyświetlmy listę wartości tego atrybutu:

In [116]:
df['fbs'].values

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0])

In [117]:
(df['fbs'].isin([0, 1])).all()

True

# Według naszego sprawdzenia, dane w tej kolumnie sa poprawne. Sprawdźmy czy jeśli nadpiszemy dane to nasze sprawdzenie zadziała.

In [118]:
df.at[0,'fbs']=-1
df['fbs'].values

array([-1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  0,  1,  0,  0,
        0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,
        0,  0,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0,  0,  1,  1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,
        0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  1,  0,  1,  0,
        1,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0,
        0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0,
        0,  0,  0,  1,  0,  0,  1,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,
        0,  0,  0,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  0,  0,  1,  0,  0])

In [119]:
(df['fbs'].isin([0, 1])).all()

False

# Jak widać nasze sprawdzenie działa. Zatem wracamy do wartości poprzednich:

In [120]:
df.at[0,'fbs']=1
df['fbs'].values

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0])

# Przejrzyjmy jeszcze raz informacje na temat atrybutów:

In [121]:
heart_disease.variables['description']

0                                                      None
1                                                      None
2                                                      None
3     resting blood pressure (on admission to the hospital)
4                                         serum cholestoral
5                           fasting blood sugar > 120 mg/dl
6                                                      None
7                               maximum heart rate achieved
8                                   exercise induced angina
9        ST depression induced by exercise relative to rest
10                                                     None
11      number of major vessels (0-3) colored by flourosopy
12                                                     None
13                               diagnosis of heart disease
Name: description, dtype: object

# Sprawdźmy jak wyglądają poszczególne wartości atrybutów:

In [122]:
for column in df.columns:
    print(f'{column}:\n{df[column].values}')

age:
[63 67 67 37 41 56 62 57 63 53 57 56 56 44 52 57 48 54 48 49 64 58 58 58
 60 50 58 66 43 40 69 60 64 59 44 42 43 57 55 61 65 40 71 59 61 58 51 50
 65 53 41 65 44 44 60 54 50 41 54 51 51 46 58 54 54 60 60 54 59 46 65 67
 62 65 44 65 60 51 48 58 45 53 39 68 52 44 47 53 51 66 62 62 44 63 52 59
 60 52 48 45 34 57 71 49 54 59 57 61 39 61 56 52 43 62 41 58 35 63 65 48
 63 51 55 65 45 56 54 44 62 54 51 29 51 43 55 70 62 35 51 59 59 52 64 58
 47 57 41 45 60 52 42 67 55 64 70 51 58 60 68 46 77 54 58 48 57 54 35 45
 70 53 59 62 64 57 52 56 43 53 48 56 42 59 60 63 42 66 54 69 50 51 62 68
 67 69 45 50 59 50 64 57 64 43 45 58 50 55 62 37 38 41 66 52 56 46 46 64
 59 41 54 39 53 63 34 47 67 54 66 52 55 49 74 54 54 56 46 49 42 41 41 49
 61 60 67 58 47 52 62 57 58 64 51 43 42 67 76 70 57 44 58 60 44 61 42 59
 40 42 61 66 46 71 59 64 66 39 57 58 57 47 55 35 61 58 58 56 56 67 55 44
 63 63 41 59 57 45 68 57 57]
sex:
[1 1 1 1 0 1 0 0 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 1 0 0 0 1 1 0 1 1 1 1 1 1
 1 1 1 0 1 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 1 1 1 1 0 1 1 1
 1 0 1 0 1 1 1 0 1 1 1 1 1 0 0 1 0 1 0 0 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 1
 1 0 0 1 1 0 1 1 1 0 1 1 1 0 0 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 0 0 1 1 1 1 1 1 1 1 1 0 0 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1 1 0 0 1
 1 1 1 1 1 0 0 1 1 0 0 1 0 0 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0
 0 1 0 1 1 0 0 1 0 0 1 1 1 0 1 1 0 0 1 0 1 1 1 1 1 1 1 1 0 1 0 0 0 1 1 0 0
 0 1 1 1 1 1 1 1 1 1 0 1 1 0 0 1 0 1 1 0 1 1 1 0 1 1 1 0 1 1 0 1 1 0 1 1 1
 0]
cp:
[1 4 4 3 2 2 4 4 4 4 4 2 3 2 3 3 2 4 3 2 1 1 2 3 4 3 3 1 4 4 1 4 3 4 3 4 4
 4 4 3 4 1 2 3 4 3 3 4 3 3 2 4 4 2 4 4 3 4 3 1 4 3 4 3 4 4 3 3 4 3 3 4 4 4
 4 3 4 3 2 4 4 4 3 3 2 3 3 4 3 4 4 3 3 3 4 4 4 2 4 4 1 4 3 3 2 4 3 4 4 4 4
 1 4 3 2 3 4 4 4 4 4 3 4 1 2 4 4 2 4 3 3 2 4 3 2 4 2 4 3 2 1 2 3 3 3 4 3 2
 3 1 4 3 4 4 4 4 4 4 3 2 4 3 4 3 4 2 4 2 3 4 4 4 4 4 4 4 3 3 4 4 1 1 4 2 3
 2 2 3 3 4 4 3 4 1 4 2 1 4 4 3 3 4 4 4 4 2 4 3 1 3 4 4 1 2 4 4 4 3 3 3 4 4
 2 4 3 4 4 3 4 3 2 3 4 4 4 2 2 2 2 4 1 3 4 4 4 4 2 4 4 4 3 4 3 4 3 2 2 3 2
 1 3 4 4 3 4 3 4 4 4 4 1 1 3 3 2 4 4 3 4 2 4 4 4 2 2 3 2 4 4 4 2 4 4 1 4 4
 2]
trestbps:
[145 160 120 130 130 120 140 120 130 140 140 140 130 120 172 150 110 140
 130 130 110 150 120 132 130 120 120 150 150 110 140 117 140 135 130 140
 120 150 132 150 150 140 160 150 130 112 110 150 140 130 105 120 112 130
 130 124 140 110 125 125 130 142 128 135 120 145 140 150 170 150 155 125
 120 110 110 160 125 140 130 150 104 130 140 180 120 140 138 138 130 120
 160 130 108 135 128 110 150 134 122 115 118 128 110 120 108 140 128 120
 118 145 125 118 132 130 135 140 138 130 135 130 150 100 140 138 130 200
 110 120 124 120  94 130 140 122 135 145 120 120 125 140 170 128 125 105
 108 165 112 128 102 152 102 115 160 120 130 140 125 140 118 101 125 110
 100 124 132 132 126 112 160 142 174 140 145 152 108 132 130 130 124 134
 148 178 158 140 120 160 192 140 129 140 138 120 100 160 138 120 160 110
 180 150 140 110 142 128 144 130 150 120 120 130 178 112 120 105 138 130
 138 112 108  94 123 108 118 112 152 110 112 136 180 118 120 160 122 130
 120 134 120 110 126 130 134 120 120 100 110 125 128 110 146 128 120 115
 120 106 140 156 124 118 136 150 120 138 136 126 152 130 140 160 140 112
 134 170 146 138 154 130 110 130 128 122 148 114 170 130 120 152 132 120
 140 124 120 164 140 110 144 130 130]
chol:
[233 286 229 250 204 236 268 354 254 203 192 294 256 263 199 168 229 239
 275 266 211 283 284 224 206 219 340 226 247 167 239 230 335 234 233 226
 177 276 353 243 225 199 302 212 330 230 175 243 417 197 198 177 290 219
 253 266 233 172 273 213 305 177 216 304 188 282 185 232 326 231 269 254
 267 248 197 360 258 308 245 270 208 264 321 274 325 235 257 234 256 302
 164 231 141 252 255 239 258 201 222 260 182 303 265 188 309 177 229 260
 219 307 249 186 341 263 203 211 183 330 254 256 407 222 217 282 234 288
 239 220 209 258 227 204 261 213 250 174 281 198 245 221 288 205 309 240
 243 289 250 308 318 298 265 564 289 246 322 299 300 293 277 197 304 214
 248 255 207 288 282 160 269 226 249 394 212 274 233 184 315 246 274 409
 244 270 305 195 240 246 283 254 196 298 294 211 299 234 236 244 273 254
 325 126 313 211 309 259 200 262 244 215 231 214 228 230 193 204 243 303
 271 268 267 199 282 269 210 204 277 206 212 196 327 149 269 201 286 283
 249 271 295 235 306 269 234 178 237 234 275 212 208 201 218 263 295 303
 209 223 197 245 261 242 319 240 226 166 315 218 223 180 207 228 311 149
 204 227 278 220 232 197 335 253 205 192 203 318 225 221 240 212 342 169
 187 197 157 176 241 264 193 131 236]
fbs:
[1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1
 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1
 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0
 0]
restecg:
[2 2 2 0 2 0 2 0 2 2 0 2 2 0 0 0 0 0 0 0 2 2 2 2 2 0 0 0 0 2 0 0 0 0 0 0 2
 2 0 0 2 0 0 0 2 2 0 2 2 2 0 0 2 2 0 2 0 2 2 2 0 2 2 0 0 2 2 2 2 0 0 0 0 2
 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 0 0 2 0 2 2 0 2 2 2 2 2 0 0 0 2 0 0 2 2
 2 2 0 0 2 0 2 2 2 2 0 0 2 2 2 0 0 0 2 0 2 2 0 2 0 2 0 2 0 2 0 0 2 0 2 0 2
 0 0 2 2 2 2 2 0 2 2 0 0 2 0 2 0 0 2 2 0 0 2 0 2 2 0 0 2 0 2 2 2 2 2 2 0 0
 0 2 2 0 0 0 2 2 2 2 0 2 2 0 0 0 0 2 2 2 0 0 0 0 2 0 0 2 0 2 0 2 2 2 0 0 0
 0 0 0 2 2 2 1 2 2 0 2 2 2 0 0 0 0 0 0 0 0 0 2 0 2 0 0 0 2 0 0 0 1 2 0 0 2
 0 0 2 0 0 0 0 2 2 0 0 0 2 2 0 2 0 0 0 1 0 0 1 2 2 0 2 0 0 2 0 0 2 0 0 0 0
 2]
thalach:
[150 108 129 187 172 178 160 163 147 155 148 153 142 173 162 174 168 160
 139 171 144 162 160 173 132 158 172 114 171 114 151 160 158 161 179 178
 120 112 132 137 114 178 162 157 169 165 123 128 157 152 168 140 153 188
 144 109 163 158 152 125 142 160 131 170 113 142 155 165 140 147 148 163
  99 158 177 151 141 142 180 111 148 143 182 150 172 180 156 160 149 151
 145 146 175 172 161 142 157 158 186 185 174 159 130 139 156 162 150 140
 140 146 144 190 136  97 132 165 182 132 127 150 154 143 111 174 175 133
 126 170 163 147 154 202 186 165 161 125 103 130 166 164 159 184 131 154
 152 124 179 170 160 178 122 160 145  96 109 173 171 170 151 156 162 158
 122 175 168 159 156 138 112 111 143 157 132  88 147 105 162 173 166 150
 178 145 161 179 194 120 195 146 163 122 106 115 125 131 152 162 125 159
 154 173 133 161 147 130 126 155 154 170 182 168 165 160 162 172 152 122
 182 172 167 179  95 169 192 143 172 108 132 169 117 126 121 163 116 103
 144 162 162 153 163 163 145  96  71 156 118 168 140 126 105 105 157 181
 173 142 116 143 141 149 152 171 169 125 125 134 181 150 138 138 120 125
 162 155 152 152 164 131 143 179 130 174 161 140 146 163 169 150 166 144
 144 136 182  90 123 132 141 115 174]
exang:
[0 1 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 1
 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 1 0 0 1 0 0 1 0 0 0 1 0
 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1
 0 1 0 0 0 0 1 0 1 0 1 1 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0 0
 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 1 0 1 1 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0
 1 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 1 1 1 0 1 0 1 0 1 0 0 0 1 0 0 1 0 0 1 1
 0 0 0 1 1 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0
 0 0 1 1 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 1 0 0 1
 0]
oldpeak:
[2.3 1.5 2.6 3.5 1.4 0.8 3.6 0.6 1.4 3.1 0.4 1.3 0.6 0.  0.5 1.6 1.  1.2
 0.2 0.6 1.8 1.  1.8 3.2 2.4 1.6 0.  2.6 1.5 2.  1.8 1.4 0.  0.5 0.4 0.
 2.5 0.6 1.2 1.  1.  1.4 0.4 1.6 0.  2.5 0.6 2.6 0.8 1.2 0.  0.4 0.  0.
 1.4 2.2 0.6 0.  0.5 1.4 1.2 1.4 2.2 0.  1.4 2.8 3.  1.6 3.4 3.6 0.8 0.2
 1.8 0.6 0.  0.8 2.8 1.5 0.2 0.8 3.  0.4 0.  1.6 0.2 0.  0.  0.  0.5 0.4
 6.2 1.8 0.6 0.  0.  1.2 2.6 0.8 0.  0.  0.  0.  0.  2.  0.  0.  0.4 3.6
 1.2 1.  1.2 0.  3.  1.2 0.  0.  1.4 1.8 2.8 0.  4.  1.2 5.6 1.4 0.6 4.
 2.8 0.  0.  0.4 0.  0.  0.  0.2 1.4 2.6 1.4 1.6 2.4 0.  0.2 0.  1.8 0.6
 0.  1.  0.  0.  0.  1.2 0.6 1.6 0.8 2.2 2.4 1.6 0.  1.2 1.  0.  0.  1.6
 1.  0.  0.  0.  0.  0.  2.9 0.  0.  1.2 2.  1.2 0.1 2.1 1.9 0.  0.5 1.9
 0.8 4.2 0.  0.  0.8 0.  0.  2.  0.  4.2 1.9 1.5 0.9 0.1 0.2 1.1 0.  0.
 0.  0.2 0.2 0.  0.  3.  0.9 0.  1.4 0.  3.8 2.  1.  0.  1.9 0.  0.  2.
 0.  0.  0.  0.  2.  1.8 0.7 0.1 0.  0.  0.1 0.1 3.4 0.8 0.2 0.  3.2 1.6
 0.8 0.  0.  0.  0.  0.  2.6 0.  1.  0.1 1.  1.  0.  1.5 2.  0.2 0.6 1.2
 0.  0.3 1.1 0.  0.3 0.3 0.  0.9 0.  3.6 1.8 2.2 0.  0.  1.9 2.3 1.8 1.6
 0.8 0.6 0.  0.  0.  0.6 3.  0.  2.  0.  0.  4.4 2.8 0.  0.  0.8 1.2 2.8
 4.  0.  0.  1.  0.2 1.2 3.4 1.2 0. ]
slope:
[3 2 2 3 1 1 3 1 2 3 2 2 2 1 1 1 3 1 1 1 2 1 2 1 2 2 1 3 1 2 1 1 1 2 1 1 2
 2 2 2 2 1 1 1 1 2 1 2 1 3 1 1 1 1 1 2 2 1 3 1 2 3 2 1 2 2 2 1 3 2 1 2 2 1
 1 1 2 1 2 1 2 2 1 2 1 1 1 1 1 2 3 2 2 1 1 2 2 1 1 1 1 1 1 2 1 1 2 2 2 2 2
 2 2 2 2 1 1 1 2 1 2 2 3 2 2 3 2 1 1 2 1 1 1 2 2 3 2 2 2 1 2 1 2 2 1 2 1 1
 1 2 2 2 2 3 2 1 1 2 1 1 1 2 2 1 1 1 1 2 2 1 2 2 2 2 1 2 1 1 2 2 1 3 1 1 3
 2 1 2 1 2 2 2 2 2 2 1 1 1 1 1 1 1 2 2 2 1 2 1 2 2 2 1 2 1 2 2 1 1 1 1 2 2
 1 1 1 2 1 2 2 1 1 1 2 3 1 2 1 1 1 1 2 1 2 1 2 1 1 2 2 2 1 2 2 1 2 1 1 2 1
 1 1 2 2 2 1 1 1 1 2 2 1 2 2 2 1 2 2 1 2 1 1 3 2 1 3 2 1 3 1 2 1 2 2 2 2 2
 2]
ca:
[0. 3. 2. 0. 0. 0. 2. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2.
 2. 0. 0. 0. 0. 0. 2. 2. 0. 0. 0. 0. 0. 1. 1. 0. 3. 0. 2. 0. 0. 1. 0. 0.
 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 0. 3. 0. 1. 2. 0. 0. 0. 0. 0. 2.
 2. 2. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 3. 0. 0. 1. 1.
 2. 1. 0. 0. 0. 1. 1. 3. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 3. 1. 2.
 3. 0. 0. 1. 0. 2. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 3. 0. 0. 1. 0. 0. 0. 1. 1. 3. 0. 2. 2. 1. 0. 3. 0. 0. 2. 0. 1. 0. 0.
 1. 0. 0. 0. 2. 1. 3. 1. 1. 3. 0. 2. 2. 0. 0. 2. 0. 3. 1. 3. 0. 3. 3. 0.
 2. 1. 0. 0. 0. 0. 0. 1. 0. 0. 3. 2. 0. 0. 0. 0. 0. 0. 2. 1. 0. 0. 0. 2.
 0. 0. 0. 0. 2. 2. 0. 0. 1. 1. 1. 0. 0. 3. 1. 1. 2. 0. 0. 0. 0. 0. 0. 0.
 2. 0. 0. 1. 1. 2. 0. 0. 1. 1. 0. 0. 0. 2. 0. 0. 0. 1. 2. 0. 0. 1. 0. 1.
 0. 0. 1. 0. 2. 0. 2. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 3. 2. 0. 0. 0. 0. 0.
 2. 0. 0. 2. 0. 0. 2. 1. 1.]
thal:
[6. 3. 7. 3. 3. 3. 3. 3. 7. 7. 6. 3. 6. 7. 7. 3. 7. 3. 3. 3. 3. 3. 3. 7.
 7. 3. 3. 3. 3. 7. 3. 7. 3. 7. 3. 3. 7. 6. 7. 3. 7. 7. 3. 3. 3. 7. 3. 7.
 3. 3. 3. 7. 3. 3. 7. 7. 7. 7. 3. 3. 7. 3. 7. 3. 7. 7. 3. 7. 7. 3. 3. 7.
 7. 6. 3. 3. 7. 3. 3. 7. 3. 3. 3. 7. 3. 3. 3. 3. 3. 3. 7. 7. 3. 3. 7. 7.
 7. 3. 3. 3. 3. 3. 3. 7. 7. 7. 7. 7. 7. 7. 3. 6. 7. 7. 6. 3. 3. 7. 7. 7.
 7. 3. 7. 3. 3. 7. 7. 3. 3. 7. 7. 3. 3. 3. 3. 7. 7. 7. 3. 3. 7. 3. 7. 7.
 3. 7. 3. 3. 3. 7. 3. 7. 7. 3. 3. 7. 7. 7. 7. 7. 3. 3. 3. 3. 7. 3. 7. 3.
 7. 7. 3. 3. 6. 7. 7. 6. 3. 3. 7. 7. 3. 7. 3. 3. 7. 6. 7. 7. 3. 7. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 7. 7. 7. 7. 7. 7. 3. 3. 3. 7. 3. 7. 3. 7. 3. 3. 3.
 3. 3. 3. 3. 7. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 7. 7. 3. 3. 3. 3. 3.
 3. 3. 3. 7. 3. 7. 3. 6. 7. 7. 3. 3. 3. 3. 3. 3. 7. 3. 3. 3. 3. 3. 6. 6.
 7. 3. 7. 6. 7. 3. 3. 7. 3. 3. 3. 3. 7. 3. 7. 3. 7. 6. 6. 7. 3. 7. 3. 6.
 7. 3. 3. 6. 7. 7. 7. 7. 3.]
num:
[0 2 1 0 0 0 3 0 2 1 0 0 2 0 0 0 1 0 0 0 0 0 1 3 4 0 0 0 0 3 0 2 1 0 0 0 3
 1 3 0 4 0 0 0 1 4 0 4 0 0 0 0 2 0 1 1 1 1 0 0 2 0 1 0 2 2 1 0 2 1 0 3 1 1
 1 0 1 0 0 3 0 0 0 3 0 0 0 0 0 0 3 0 0 0 1 2 3 0 0 0 0 0 0 3 0 2 1 2 3 1 1
 0 2 2 0 0 0 3 2 3 4 0 3 1 0 3 3 0 0 0 0 0 0 0 0 4 3 1 0 0 1 0 1 0 1 4 0 0
 0 0 0 0 4 3 1 1 1 2 0 0 4 0 0 0 0 0 1 0 3 0 1 0 4 1 0 1 0 0 3 2 0 0 1 0 0
 2 1 2 0 3 2 0 3 0 0 0 1 0 0 0 0 0 3 3 3 0 1 0 4 0 3 1 0 0 0 0 0 0 0 0 3 1
 0 0 0 3 2 0 2 1 0 0 3 2 1 0 0 0 0 0 2 0 2 2 1 3 0 0 1 0 0 0 0 0 0 0 1 0 3
 0 0 4 2 2 1 0 1 0 2 0 1 0 0 0 1 0 2 0 3 0 2 4 2 0 0 1 0 2 2 1 0 3 1 1 2 3
 1]

# Możemy zauważyć, że podobną weryfikację możemy przeprowadzić w atrybutach "exang" oraz "sex".

In [123]:
(df['sex'].isin([0, 1])).all()

True

In [124]:
(df['exang'].isin([0, 1])).all()

True

# Wszystko w porządku. Możemy przejść do reformatowania danych. W kolumnach "ca" oraz "tha" możemy zamienić format danych z float na int, ponieważ żadna z danych nie ma wartości po przecinku- ułatwi to dokładność operacji numerycznych na tych danych. Nastpęnie stworzymy kopię danych, ponieważ w dalszych krokach (analiza danych) łatwiej jest się poruszać po danych zdyskretyzowanych, a w kopii wykonamy zamianę 0 na mężczyznę(M), a 1 na kobietę (K) w kolumnie "sex" kierując się, że 1 to obecność allelu Y typowego dla płci żeńskiej.

In [125]:
df["ca"] = df['ca'].astype(int)
df['ca'].values

array([0, 3, 2, 0, 0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 3, 0, 2, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 3, 0, 1, 2,
       0, 0, 0, 0, 0, 2, 2, 2, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 3, 3, 0, 0, 1, 1, 2, 1, 0, 0, 0, 1, 1, 3, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 3, 1, 2, 3, 0, 0, 1, 0, 2, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1, 0, 0, 0, 1, 1,
       3, 0, 2, 2, 1, 0, 3, 0, 0, 2, 0, 1, 0, 0, 1, 0, 0, 0, 2, 1, 3, 1,
       1, 3, 0, 2, 2, 0, 0, 2, 0, 3, 1, 3, 0, 3, 3, 0, 2, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 3, 2, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 2, 0, 0, 0, 0,
       2, 2, 0, 0, 1, 1, 1, 0, 0, 3, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 1, 1, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0, 1, 2, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 2, 0, 2, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 3, 2, 0, 0, 0,
       0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1])

In [126]:
df["thal"] = df['thal'].astype(int)
df['thal'].values

array([6, 3, 7, 3, 3, 3, 3, 3, 7, 7, 6, 3, 6, 7, 7, 3, 7, 3, 3, 3, 3, 3,
       3, 7, 7, 3, 3, 3, 3, 7, 3, 7, 3, 7, 3, 3, 7, 6, 7, 3, 7, 7, 3, 3,
       3, 7, 3, 7, 3, 3, 3, 7, 3, 3, 7, 7, 7, 7, 3, 3, 7, 3, 7, 3, 7, 7,
       3, 7, 7, 3, 3, 7, 7, 6, 3, 3, 7, 3, 3, 7, 3, 3, 3, 7, 3, 3, 3, 3,
       3, 3, 7, 7, 3, 3, 7, 7, 7, 3, 3, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7,
       3, 6, 7, 7, 6, 3, 3, 7, 7, 7, 7, 3, 7, 3, 3, 7, 7, 3, 3, 7, 7, 3,
       3, 3, 3, 7, 7, 7, 3, 3, 7, 3, 7, 7, 3, 7, 3, 3, 3, 7, 3, 7, 7, 3,
       3, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 3, 7, 3, 7, 7, 3, 3, 6, 7, 7, 6,
       3, 3, 7, 7, 3, 7, 3, 3, 7, 6, 7, 7, 3, 7, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 7, 7, 7, 7, 7, 7, 3, 3, 3, 7, 3, 7, 3, 7, 3, 3, 3, 3, 3, 3, 3,
       7, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 7, 7, 3, 3, 3, 3, 3, 3, 3,
       3, 7, 3, 7, 3, 6, 7, 7, 3, 3, 3, 3, 3, 3, 7, 3, 3, 3, 3, 3, 6, 6,
       7, 3, 7, 6, 7, 3, 3, 7, 3, 3, 3, 3, 7, 3, 7, 3, 7, 6, 6, 7, 3, 7,
       3, 6, 7, 3, 3, 6, 7, 7, 7, 7, 3])

# Stworzymy kopię zdyskretyzowanych danych:

In [127]:
df_after_discretization = df.copy()

# A teraz zamienimy wartości w kolumnie płci:

In [128]:
df['sex'] = df['sex'].astype(str)
df['sex'] = df['sex'].map({'0': 'M', '1': 'K'})
df['sex'].values

array(['K', 'K', 'K', 'K', 'M', 'K', 'M', 'M', 'K', 'K', 'K', 'M', 'K',
       'K', 'K', 'K', 'K', 'K', 'M', 'K', 'K', 'M', 'K', 'K', 'K', 'M',
       'M', 'M', 'K', 'K', 'M', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K',
       'K', 'M', 'K', 'M', 'K', 'M', 'K', 'K', 'K', 'M', 'K', 'M', 'K',
       'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'M', 'M', 'K', 'M', 'K',
       'K', 'K', 'K', 'K', 'K', 'M', 'K', 'K', 'K', 'K', 'M', 'K', 'M',
       'K', 'K', 'K', 'M', 'K', 'K', 'K', 'K', 'K', 'M', 'M', 'K', 'M',
       'K', 'M', 'M', 'K', 'K', 'M', 'K', 'K', 'K', 'K', 'M', 'M', 'K',
       'K', 'K', 'K', 'K', 'K', 'M', 'K', 'K', 'M', 'M', 'K', 'K', 'M',
       'K', 'K', 'K', 'M', 'K', 'K', 'K', 'M', 'M', 'K', 'K', 'M', 'K',
       'K', 'K', 'K', 'M', 'M', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K',
       'K', 'K', 'K', 'K', 'K', 'M', 'K', 'M', 'M', 'K', 'K', 'K', 'K',
       'K', 'K', 'K', 'K', 'K', 'M', 'M', 'K', 'K', 'M', 'K', 'M', 'K',
       'K', 'M', 'M', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'M', 'K', 'K',
       'M', 'M', 'K', 'K', 'K', 'K', 'K', 'K', 'M', 'M', 'K', 'K', 'M',
       'M', 'K', 'M', 'M', 'K', 'M', 'K', 'K', 'K', 'K', 'K', 'M', 'M',
       'K', 'K', 'M', 'K', 'K', 'M', 'M', 'M', 'K', 'M', 'M', 'M', 'K',
       'M', 'M', 'K', 'M', 'K', 'K', 'M', 'M', 'K', 'M', 'M', 'K', 'K',
       'K', 'M', 'K', 'K', 'M', 'M', 'K', 'M', 'K', 'K', 'K', 'K', 'K',
       'K', 'K', 'K', 'M', 'K', 'M', 'M', 'M', 'K', 'K', 'M', 'M', 'M',
       'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'M', 'K', 'K', 'M',
       'M', 'K', 'M', 'K', 'K', 'M', 'K', 'K', 'K', 'M', 'K', 'K', 'K',
       'M', 'K', 'K', 'M', 'K', 'K', 'M', 'K', 'K', 'K', 'M'],
      dtype=object)

# Możemy jeszcze odwrócicć proces sykretyzacji dla decyzji (kolumna "num"), gdzie 0 to "brak zawału", a reszta liczb to kolejno "Zawał typu X":

In [129]:
# Definiowanie funkcji do mapowania
def map_num(num):
    if num == '0':
        return "brak"
    else:
        return f"Zawał typu {num}"

In [130]:
df['num'] = df['num'].astype(str)
df['num'] = df['num'].map(map_num)
df['num'].values

array(['brak', 'Zawał typu 2', 'Zawał typu 1', 'brak', 'brak', 'brak',
       'Zawał typu 3', 'brak', 'Zawał typu 2', 'Zawał typu 1', 'brak',
       'brak', 'Zawał typu 2', 'brak', 'brak', 'brak', 'Zawał typu 1',
       'brak', 'brak', 'brak', 'brak', 'brak', 'Zawał typu 1',
       'Zawał typu 3', 'Zawał typu 4', 'brak', 'brak', 'brak', 'brak',
       'Zawał typu 3', 'brak', 'Zawał typu 2', 'Zawał typu 1', 'brak',
       'brak', 'brak', 'Zawał typu 3', 'Zawał typu 1', 'Zawał typu 3',
       'brak', 'Zawał typu 4', 'brak', 'brak', 'brak', 'Zawał typu 1',
       'Zawał typu 4', 'brak', 'Zawał typu 4', 'brak', 'brak', 'brak',
       'brak', 'Zawał typu 2', 'brak', 'Zawał typu 1', 'Zawał typu 1',
       'Zawał typu 1', 'Zawał typu 1', 'brak', 'brak', 'Zawał typu 2',
       'brak', 'Zawał typu 1', 'brak', 'Zawał typu 2', 'Zawał typu 2',
       'Zawał typu 1', 'brak', 'Zawał typu 2', 'Zawał typu 1', 'brak',
       'Zawał typu 3', 'Zawał typu 1', 'Zawał typu 1', 'Zawał typu 1',
       'brak', 'Zawał typu 1', 'brak', 'brak', 'Zawał typu 3', 'brak',
       'brak', 'brak', 'Zawał typu 3', 'brak', 'brak', 'brak', 'brak',
       'brak', 'brak', 'Zawał typu 3', 'brak', 'brak', 'brak',
       'Zawał typu 1', 'Zawał typu 2', 'Zawał typu 3', 'brak', 'brak',
       'brak', 'brak', 'brak', 'brak', 'Zawał typu 3', 'brak',
       'Zawał typu 2', 'Zawał typu 1', 'Zawał typu 2', 'Zawał typu 3',
       'Zawał typu 1', 'Zawał typu 1', 'brak', 'Zawał typu 2',
       'Zawał typu 2', 'brak', 'brak', 'brak', 'Zawał typu 3',
       'Zawał typu 2', 'Zawał typu 3', 'Zawał typu 4', 'brak',
       'Zawał typu 3', 'Zawał typu 1', 'brak', 'Zawał typu 3',
       'Zawał typu 3', 'brak', 'brak', 'brak', 'brak', 'brak', 'brak',
       'brak', 'brak', 'Zawał typu 4', 'Zawał typu 3', 'Zawał typu 1',
       'brak', 'brak', 'Zawał typu 1', 'brak', 'Zawał typu 1', 'brak',
       'Zawał typu 1', 'Zawał typu 4', 'brak', 'brak', 'brak', 'brak',
       'brak', 'brak', 'Zawał typu 4', 'Zawał typu 3', 'Zawał typu 1',
       'Zawał typu 1', 'Zawał typu 1', 'Zawał typu 2', 'brak', 'brak',
       'Zawał typu 4', 'brak', 'brak', 'brak', 'brak', 'brak',
       'Zawał typu 1', 'brak', 'Zawał typu 3', 'brak', 'Zawał typu 1',
       'brak', 'Zawał typu 4', 'Zawał typu 1', 'brak', 'Zawał typu 1',
       'brak', 'brak', 'Zawał typu 3', 'Zawał typu 2', 'brak', 'brak',
       'Zawał typu 1', 'brak', 'brak', 'Zawał typu 2', 'Zawał typu 1',
       'Zawał typu 2', 'brak', 'Zawał typu 3', 'Zawał typu 2', 'brak',
       'Zawał typu 3', 'brak', 'brak', 'brak', 'Zawał typu 1', 'brak',
       'brak', 'brak', 'brak', 'brak', 'Zawał typu 3', 'Zawał typu 3',
       'Zawał typu 3', 'brak', 'Zawał typu 1', 'brak', 'Zawał typu 4',
       'brak', 'Zawał typu 3', 'Zawał typu 1', 'brak', 'brak', 'brak',
       'brak', 'brak', 'brak', 'brak', 'brak', 'Zawał typu 3',
       'Zawał typu 1', 'brak', 'brak', 'brak', 'Zawał typu 3',
       'Zawał typu 2', 'brak', 'Zawał typu 2', 'Zawał typu 1', 'brak',
       'brak', 'Zawał typu 3', 'Zawał typu 2', 'Zawał typu 1', 'brak',
       'brak', 'brak', 'brak', 'brak', 'Zawał typu 2', 'brak',
       'Zawał typu 2', 'Zawał typu 2', 'Zawał typu 1', 'Zawał typu 3',
       'brak', 'brak', 'Zawał typu 1', 'brak', 'brak', 'brak', 'brak',
       'brak', 'brak', 'brak', 'Zawał typu 1', 'brak', 'Zawał typu 3',
       'brak', 'brak', 'Zawał typu 4', 'Zawał typu 2', 'Zawał typu 2',
       'Zawał typu 1', 'brak', 'Zawał typu 1', 'brak', 'Zawał typu 2',
       'brak', 'Zawał typu 1', 'brak', 'brak', 'brak', 'Zawał typu 1',
       'brak', 'Zawał typu 2', 'brak', 'Zawał typu 3', 'brak',
       'Zawał typu 2', 'Zawał typu 4', 'Zawał typu 2', 'brak', 'brak',
       'Zawał typu 1', 'brak', 'Zawał typu 2', 'Zawał typu 2',
       'Zawał typu 1', 'brak', 'Zawał typu 3', 'Zawał typu 1',
       'Zawał typu 1', 'Zawał typu 2', 'Zawał typu 3', 'Zawał typu 1'],
      dtype=object)

# Możemy wcześniej sprawdzane warunki 0 lub 1 (oprócz kolumny "sex") zamienić na True/False.

In [131]:
df['exang'] = df['exang'].astype(bool)
df['exang'].values

array([False,  True,  True, False, False, False, False,  True, False,
        True, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
       False, False,  True, False,  True, False, False,  True, False,
        True,  True,  True,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False,  True,  True,  True,  True,
       False, False,  True, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False,  True,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
       False,  True,  True, False,  True, False, False, False, False,
        True, False,  True, False,  True,  True, False, False,  True,
        True, False, False, False,  True, False,  True, False, False,
        True, False,  True, False,  True, False, False,  True,  True,
       False, False, False, False, False, False, False, False,  True,
        True, False,  True, False, False, False, False,  True, False,
       False, False,  True,  True,  True, False,  True,  True,  True,
       False, False,  True, False,  True, False, False, False,  True,
       False, False, False, False, False,  True, False, False, False,
        True, False, False,  True, False,  True, False, False, False,
        True, False, False, False,  True,  True,  True, False,  True,
       False,  True, False,  True, False, False, False,  True, False,
       False,  True, False, False,  True,  True, False, False, False,
        True,  True, False,  True, False,  True, False,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False,  True, False,  True, False,
       False, False, False, False, False, False,  True, False,  True,
       False, False, False,  True, False, False, False, False,  True,
        True,  True, False, False,  True, False, False,  True, False])

In [132]:
df['fbs'] = df['fbs'].astype(bool)
df['fbs'].values

array([ True, False, False, False, False, False, False, False, False,
        True, False, False,  True, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False,  True, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True, False,  True, False, False,  True, False,
        True, False,  True, False, False, False,  True, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True, False,  True, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True, False, False,  True, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False])

# Wydaje mi się, że nic więcej na tym zestawie danych nie da się zrobić :)

---

## Możemy porównać jak wyglądają obydwa zestawy danych.

In [133]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63,K,1,145,233,True,2,150,False,2.3,3,0,6,brak
1,67,K,4,160,286,False,2,108,True,1.5,2,3,3,Zawał typu 2
2,67,K,4,120,229,False,2,129,True,2.6,2,2,7,Zawał typu 1
3,37,K,3,130,250,False,0,187,False,3.5,3,0,3,brak
4,41,M,2,130,204,False,2,172,False,1.4,1,0,3,brak
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57,M,4,140,241,False,0,123,True,0.2,2,0,7,Zawał typu 1
298,45,K,1,110,264,False,0,132,False,1.2,2,0,7,Zawał typu 1
299,68,K,4,144,193,True,0,141,False,3.4,2,2,7,Zawał typu 2
300,57,K,4,130,131,False,0,115,True,1.2,2,1,7,Zawał typu 3
301,57,M,2,130,236,False,2,174,False,0.0,2,1,3,Zawał typu 1

In [134]:
df_after_discretization

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63,1,1,145,233,1,2,150,0,2.3,3,0,6,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3,3,2
2,67,1,4,120,229,0,2,129,1,2.6,2,2,7,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0,3,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57,0,4,140,241,0,0,123,1,0.2,2,0,7,1
298,45,1,1,110,264,0,0,132,0,1.2,2,0,7,1
299,68,1,4,144,193,1,0,141,0,3.4,2,2,7,2
300,57,1,4,130,131,0,0,115,1,1.2,2,1,7,3
301,57,0,2,130,236,0,2,174,0,0.0,2,1,3,1

In [137]:
%%shell
jupyter nbconvert --to html ///content/WS_zad_1_155376_Adrian_Albrecht.ipynb

[NbConvertApp] Converting notebook ///content/WS_zad_1_155376_Adrian_Albrecht.ipynb to html
[NbConvertApp] Writing 708715 bytes to /content/WS_zad_1_155376_Adrian_Albrecht.html